_BASE_: "Base-RCNN-HarDNet-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_hardnet39ds_fpn_backbone"
  WEIGHTS: "https://www.dropbox.com/s/8mnz692vn683yqa/hardnet39ds-08496aae.pth?dl=1"
  MASK_ON: False
  FPN:
    OUT_CHANNELS: 128
DATASETS:
  TRAIN: ("sku110_train",)
  TEST: ("sku110_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "checkpoints/FRCN-HarDNet-39DS-FPNLite-1x"