_BASE_: "Base-RCNN-ShuffleNet-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_shufflenetv2_x1_0_fpn_backbone"
  WEIGHTS: "https://www.dropbox.com/s/sfkko4jx0pbkxlk/shufflenetv2_x1-b2834eb4.pth?dl=1"
  MASK_ON: False
  FPN:
    OUT_CHANNELS: 128
SOLVER:
  IMS_PER_BATCH: 3
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATASETS:
  TRAIN: ("sku110_train",)
  TEST: ("sku110_test",)
OUTPUT_DIR: "checkpoints/FRCN-ShuffleNetV2-FPNLite-1x"